apiVersion: server.packet.crossplane.io/v1alpha1
kind: Device
metadata:
  name: devices
  namespace: app-project1-dev
spec:
  # projectID: 93125c2a-8b78-4d4f-a3c4-7367d6b7cca8
  hostname: crossplane
  plan: c1.small.x86
  facility: any
  operatingSystem: centos_7
  billingCycle: hourly
  hardware_reservation_id: next_available
  classRef:
    name: packetclass
    namespace: packet-infra-dev
  reclaimPolicy: Delete