apiVersion: server.packet.crossplane.io/v1alpha2
kind: Device
metadata:
  name: devicea
  namespace: app-project1-dev
spec:
  forProvider:
    hostname: crossplane
    plan: c1.small.x86
    facility: any
    locked: false
    operatingSystem: centos_7
    billingCycle: hourly
    hardware_reservation_id: next_available
  providerRef:
    name: example-provider-packet
  writeConnectionSecretToRef:
    name: devicea-conn
    namespace: crossplane-system
