apiVersion: server.packet.crossplane.io/v1alpha1
kind: DeviceClass
metadata:
  name: packetclass
  namespace: app-project1-dev
specTemplate:
  project_id: 93125c2a-8b78-4d4f-a3c4-7367d6b7cca8
  plan: c1.small.x86
  facility: [any]
  operating_system: centos_7
  billing_cycle: hourly
  # hardware_reservation_id: next_available
  providerRef:
    name: example
    namespace: packet-infra-dev
  reclaimPolicy: Delete