---
apiVersion: v1
kind: Secret
metadata:
  name: example-provider-packet
  namespace: packet-infra-dev
type: Opaque
data:
  credentials: BASE64ENCODED_PACKET_PROVIDER_CREDS
---
apiVersion: packet.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentialsSecretRef:
    name: example-provider-packet
    namespace: packet-infra-dev
    key: credentials
