---
apiVersion: v1
kind: Secret
metadata:
  name: example-provider-equinix-metal
  namespace: crossplane-system
type: Opaque
data:
  credentials: BASE64ENCODED_METAL_PROVIDER_CREDS
---
apiVersion: metal.equinix.com/v1beta1
kind: ProviderConfig
metadata:
  name: equinix-metal-provider
spec:
  credentialsSecretRef:
    name: example-provider-equinix-metal
    namespace: crossplane-system
    key: credentials
