name: Install Provider

on: pull_request

jobs:
  install-provider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0

      - name: Build
        run: ./build/run make build.all

      - name: E2E
        run: ./build/run make e2e USE_HELM3=true


