name: Install Provider

on: pull_request

jobs:
  install-provider:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU
        run: DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends binfmt-support qemu-user-static

      - name: Register QEMU with Docker
        run: docker run --rm --privileged hypriot/qemu-register

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Build
        run: ./build/run make build.all

      - name: E2E
        run: ./build/run make e2e USE_HELM3=true
